### PR TITLE
Build: Auto-load fixtures (fixes #54)

### LINKED ISSUE #54: Consider using "requireindex" package to simplify test fixture consumption
Right now, in order to add new test fixtures, some manual work must be done (adding to `test/fixtures/index.js`, etc.). I am wondering if the "requireindex" package might be able to do some of this dynamically.

### PR DESCRIPTION
**Pull request by cvisco**
This mimics the behavior of npm module `requireindex`, but loads the
fixture files as raw text, instead of interpretted JavaScript code.

### CODE REVIEW

**Comment by cvisco** [comment]
@platinumazure we can't use requireindex here because we don't want it to load the fixtures as actual JavaScript code. This accomplishes the same sort of thing while giving us raw text output instead.

**Comment by platinumazure** [comment]
Ah, yeah, that's a good point. I should have thought of that. I'll review
tonight. If it looks good, would you prefer I merge or leave a comment?

**Comment by cvisco** [comment]
@platinumazure if it looks OK, feel free to just merge it.

**Comment by platinumazure** [comment]
LGTM, nice work.

Noticing that the recent `one-dependency-per-line` changes seem to have LF vs CRLF conflicts when I run the tests on my box-- we might need to look at `.gitattributes` and decide how we want to go forward. Obviously that is unrelated to this PR.

**Pull request merged**
