### PR TITLE
Update: sort-amd-paths should consider "/" before anything else (fixe…

### PR DESCRIPTION
**Pull request by obrejla**
This is imho the right behavior.

### CODE REVIEW

**Comment by platinumazure** [comment]
Your call, but I wonder if the implementation is conceptually simpler if you split the path on the `'/'` character, and then compare on number of segments and pairwise on individual path segments. What do you think?

**Comment by obrejla** [comment]
Imho this is pretty simple. Char-by-char common compare and if there is a `"/"`, then just say that it should be first. If everything is equal, then compare lengths. Nothing more, nothing less.

**Comment by platinumazure** [comment]
Can you document the performance before and after your implementation?

**Comment by obrejla** [comment]
Measured on Mac
repository: 41MB
JavaScript files: 2389

Current implementation v0.9.2:
✖ 787 problems (787 errors, 0 warnings)
real    0m30.829s
user    0m29.361s
sys 0m1.689s

Patched implementation:
✖ 773 problems (773 errors, 0 warnings)
real    0m31.838s
user    0m30.037s
sys 0m1.660s

It seems to be ok ;)

**Comment by cvisco** [comment]
While i'm convinced there exists a tighter, faster implementation for this, we can always refactor it. This works and doesn't seem to add _too_ much extra overhead. As long as it doesn't break anything—and it seems not to—I'm good with merging it. :)

**Comment by obrejla** [comment]
Yep exactly...good enough impkementation is good enough ;)

**Pull request merged**
